### ISSUE TITLE
Role permissions matrix navigation

### ISSUE THREAD

**Issue by Steve-Akers** [CenturyLinkCloud/PublicKB#1142]
PublicKB/Accounts & Users/role-permissions-matrix.md

Scroll bar for role permissions matrix is at bottom of very long list.  
When I first opened this matrix, I needed to see a column that was off to the right.
I scrolled to the bottom of the document to expose the scroll bar at the bottom to use my mouse to scroll to the right.  I lost track of the section that I was trying to verify when scrolling back up because the 1st column had scrolled off the screen, now it was just permissions with no context.

**Comment by chrislittle** [comment]
We should probably convert this matrix to a filter system of some kind by role & action group.

**Comment by rpdubose** [comment]
Move to JIRA for planning.
