### ISSUE TITLE
OwnCloud KB missing script

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PublicKB#125]
https://www.centurylinkcloud.com/knowledge-base/ecosystem-partners/getting-started-with-owncloud-blueprint/

the script referenced in this KB is not available globally.  "Install ownCloud on Linux" thus this is non-functional

**Comment by hk1232** [comment]
Script is published and visible.  This should be closed.

https://control.ctl.io/Blueprints/Packages/Details?uuid=bf6bdfba-593d-443c-b490-399276d9b8b6&classification=Script&type=AccountLibrary#

![image](https://cloud.githubusercontent.com/assets/7604630/7596012/3e2087e4-f8b0-11e4-98b3-b25442532836.png)
