### ISSUE TITLE
lbaas missing 

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PublicKB#1336]
https://www.ctl.io/knowledge-base/lbaas/ is missing from the main kb page list.

**Comment by rpdubose** [comment]
@chrislittle This was actually the what the product team requested. All of their KBs are here: https://www.ctl.io/knowledge-base/network/

Though it's not significant for a separate folder to be created. I'll ask Matt the next time I see him.

**Comment by chrislittle** [comment]
@rpdubose I don't see either of the kbs in the /lbaas in /network both in the repo nor the live KB.  you can only find the 2 lbaas kb's using search not just a simple click an area.  if they need to be moved they should to /network

**Comment by rpdubose** [comment]
Corrected.
