### ISSUE TITLE
Missing pages

### ISSUE THREAD

**Issue by rchakra1** [CenturyLinkCloud/PublicKB#1559]
The following pages are missing from KB

https://www.ctl.io/knowledge-base/cloud-application-manager/autodiscover-clc-instances/
https://www.ctl.io/knowledge-base/cloud-application-manager/autodiscover-ec2-instances/

Please restore them under https://www.ctl.io/knowledge-base/cloud-application-manager/deploying-anywhere/

**Comment by david-lynn-dev** [comment]
@rchakra1 Closing old issue.
