### ISSUE TITLE
404 on KB Page

### ISSUE THREAD

**Issue by andrewBrunette** [CenturyLinkCloud/PublicKB#182]
the following page is throwing a 404: 
https://www.centurylinkcloud.com/knowledge-base/ecosystem-partners/migrate-appfog-addon-to-addon-engine/

**Comment by hk1232** [comment]
Clarification - this link is showing up in the site search but the page was removed.

I also created a pull request the other day to update the redirects file so I wouldn't expect this to happen.  Not sure if that was merged into prod yet or not.

**Comment by nathanyoung** [comment]
just merged it, going out now.
