### ISSUE TITLE
"the lesser of 4 Sockets or 24 cores" only applies to physical servers

### ISSUE THREAD

**Issue by SQLPROCtologist** [CenturyLinkCloud/PublicKB#1959]
The verbiage in the "Licensing Impact" paragraph should be modified slightly in order to accommodate virtual cores. Per Microsoft documentation, “In a virtualized environment, the compute capacity limit is based on the number of logical processors…”
Source: https://docs.microsoft.com/en-us/sql/sql-server/compute-capacity-limits-by-edition-of-sql-server

Licensing Impact
Many vendors license and/or limit their applications and services based on any one of the 3 items above. For example, Microsoft SQL Server 2016 limits Standard Edition to **the lesser of 4 Sockets or 24 cores**. Thus customers who want to leverage more than 4 vCPUs on CenturyLink Cloud would need to leverage Enterprise Edition which does not impose such limits. Customers should carefully review each vendors licensing terms against the delivery model used on CenturyLink Cloud to make sure they comply with those terms and are not procuring more compute than a product is capable of consuming.
Source: https://www.ctl.io/knowledge-base/servers/platform-socket-to-vcpu-allocation

**Comment by david-lynn-dev** [comment]
@SQLPROCtologist Closing old issue
