### ISSUE TITLE
404 on Visio Stencils KB

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PublicKB#201]
the visio stencils kb @ https://www.centurylinkcloud.com/knowledge-base/general/centurylink-cloud-visio-stencils/ is 404.  the repository has the .md file in general (centuryLink-cloud-visio-stencils.md) and I'm not aware of any updates so i'm unclear why its missing from the live site

**Comment by chrislittle** [comment]
another KB with 404
https://www.centurylinkcloud.com/knowledge-base/managed-services/managed-backup-frequently-asked-questions/

**Comment by nathanyoung** [comment]
moving this bug to the correct repo
