### ISSUE TITLE
Add external link parser?

### ISSUE THREAD

**Issue by thenickcox** [CenturyLinkCloud/PublicKB#238]
Originally, I had written a fourth parser (in addition to the markdown parser, front matter parser, and file link parser) that checked the output of external links. I didn't include it in the Commit Analyzer because, on this repo, the build made Travis CI timeout. (Max time for a build is 50 minutes.)

@mattfordham and I proposed tabling that parser for the time being in order to encourage a quick build. (Currently, this repo [builds at 29 seconds](https://travis-ci.org/CenturyLinkCloud/PublicKB).)

This morning, I was tinkering with the external link parser and fixed a bug in the link parser that got it down to 17 minutes on my local machine. (This will likely be a good bit slower on Travis because of the limited hardware. It's difficult to estimate just how much slower, but I don't believe it would be more than 2x.) That puts it, in my opinion, in the realm of consideration.

There are likely more optimizations I could make to get that time down further. Is that something you'd be interested in investing some hours into, or should we leave it as is? Is there a ballpark build time that you'd like to try to stay within, so we could consider if it was even possible to get the link parser to run within that time budget? 

Further, If we decide to leave the link parser as is, then should it be added it to the commit analyzer, or should we keep it out for the sake of speedy builds? You'd have to weigh whether the trade off of the time-to-build was worth it.

Worst case, [here](https://gist.github.com/thenickcox/40e9c578f11ca0cbb22f) is a link to a gist of the output of the external link parser. That could at least give you a sense of what needs fixing, and then you could decide if it's worth trying to add it to the build, or just decide to place the onus of link checking on the authors.

(This issue was added to this repo because of the three that contain the commit analyzer, this has the greatest number of files.)

cc @nathanyoung 

## Edit

An optimization I just tried [in this commit](https://github.com/CenturyLinkCloud/KB-Commit-Analyzer/commit/3b2ae2299ada235653ab3a9056727e1817887d0c) dropped the build time to 13:18. That was the low-hanging fruit. More optimizations could be done, I'm sure, but not without a good bit more investment.

**Comment by nathanyoung** [comment]
No, let's leave it out. I'll go through and cleanup the existing links. 

Perhaps you could add the external parser in a branch so it could be run locally on a monthly basis?

**Comment by thenickcox** [comment]
In order to avoid the headache of [tracking the submodule branches in this project](http://stackoverflow.com/questions/1777854/git-submodules-specify-a-branch-tag), I could just add it to a branch in the commit analyzer that someone could conceivably check out and replace with their local `/lib` directory in, for example, this repo.
