### ISSUE TITLE
'updated' not 'update' in AppFog Blue/Green deployment artcile

### ISSUE THREAD

**Issue by osbornm** [CenturyLinkCloud/PublicKB#243]
https://www.ctl.io/knowledge-base/appfog/blue-green-deployments/#put-update-application-into-main-rotation

**Comment by csterwa** [comment]
Resolved in pull request @osbornm - thx!

**Comment by osbornm** [comment]
FYI: if you reference the issue in the PR it will close the issue when the PR is merged.
