### ISSUE TITLE
Subfolders in Server Category

### ISSUE THREAD

**Issue by mcaminiti** [CenturyLinkCloud/PublicKB#3]
Can we get a Linux vs Windows subcategory in the Servers section to at least filter or minimize the amount of articles in the section? There are 60 articles to browse through and while we can always search, having an area for those base OS's would be helpful.

**Comment by nathanyoung** [comment]
This would also be helpful in the Managed Services category

* Operating Systems
* Directory Services
* Database
* Middleware
* Web Servers
* Other Managed Services

**Comment by nathanyoung** [comment]
request captured and moved to trello
