### ISSUE TITLE
Markdown Headings are valid with or without a space after the #

### ISSUE THREAD

**Issue by osbornm** [CenturyLinkCloud/PublicKB#319]
Currently whatever parser we are using requires that there be a space between the # and text to generate a proper H tag. It is valid markdown if there is no space and most editors will generate it like that so we are seeing lots of PR where they have to fix this. We should just allow it. 

@mattfordham how big of a change is this, just as a spit ball?

**Comment by nathanyoung** [comment]
cc: @dmak78 @thenickcox 

@mattfordham is on vacation.

**Comment by osbornm** [comment]
Who approved that!? :trollface:

**Comment by thenickcox** [comment]
Just wanted to get back to you quickly on this. We're using a [third party markdown parsing library](https://github.com/chjj/marked) that doesn't, at first glance, allow configuration of making affordances for things like that. We can research early next week if there are other options, but for now, unfortunately, we don't have any control over the markdown parsing.

**Comment by thenickcox** [comment]
Bump @osbornm cc @nathanyoung. Just didn't want this to slip through the cracks.

**Comment by nathanyoung** [comment]
Is it possible for the commit analyzer to check to make sure headers have a trailing space?

**Comment by osbornm** [comment]
Yes but the real problem is that it's valid markdown and many markdown editors make headings that way.

Cheers,
Matthew M. Osborn

On Aug 26, 2015, at 11:13, Nathan Young <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible for the commit analyzer to check to make sure headers have a trailing space?

-

**Comment by keithresar** [comment]
FWIW at one point our parser was leading space agnostic - I swear this rendered fine in my pages:

```
###Heading
```

I discovered this changed at some point and needed to update all the KBs that were missing that space.
