### ISSUE TITLE
ctl-community slack badge

### ISSUE THREAD

**Issue by keithresar** [CenturyLinkCloud/PublicKB#336]
The Orchestrate team has a great thing setup - self-registration of a community help channel.  Thinking of the same to supplement our developer central site so folks have real-time access into a slack community.

What are some thoughts on getting this added into the Developer Center site?

```
<script async defer src="http://ctl-community-slackin.useast.appfog.ctl.io/slackin.js"></script>
```
Default minimized:
![image](https://cloud.githubusercontent.com/assets/7604630/9504141/8e6fd206-4c00-11e5-8819-c1b0dabb0d06.png)

Default expanded on click:
![image](https://cloud.githubusercontent.com/assets/7604630/9504147/9a870280-4c00-11e5-80bc-00b99942ca71.png)

**Comment by nathanyoung** [comment]
wrong repo?
