### ISSUE TITLE
Best practices for Eco KB article impression tracking

### ISSUE THREAD

**Issue by keithresar** [CenturyLinkCloud/PublicKB#337]
We're finally collecting data on all Eco Blueprint deployments and looking at making this available to partners (and ourselves) via a partner portal.

I'd like to collect data on Eco KB impressions that we can display alongside the deploy data.

What are your thoughts on just including a link to an off-site image with a unique URL so we can capture this data?  This is independent of any other existing tracking systems operational for the overall ctl.io site.

**Comment by nathanyoung** [comment]
This data is available via our Google Analytics account. If you have a google account, I can add you to our analytics account.

Here's the view:
https://www.google.com/analytics/web/?hl=en#report/content-pages/a45856849w76637963p79226068/%3Fexplorer-table.filter%3D%2Fknowledge-base%2Fecosystem-partners%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowStart%3D0%26explorer-table.rowCount%3D250/

![Uploading Screen Shot 2015-08-26 at 12.57.25 PM.png…]()

**Comment by nathanyoung** [comment]
![screen shot 2015-08-26 at 12 57 25 pm](https://cloud.githubusercontent.com/assets/1447339/9504552/07c39e58-4bf2-11e5-9e78-99b2ffc41d2e.png)

**Comment by keithresar** [comment]
Yeah.. so that's not my ask.

I'd like to connect impressions and their Blueprint UUID with actual deploys and make this visible to our partners in real time.

**Comment by rpdubose** [comment]
@keithresar, per my comment in slack.  Can we hit the brakes until next wk when return from vacation? This doesn't feel like an emergency.  I'm not in favor of having tribal analytics and would like the opportunity to collaborate on this. You let me know if that posses too much of a hardship for you.

**Comment by keithresar** [comment]
Not a hardship at all.. thought this was the best place for a placeholder to pick up when the time is right.

**Comment by rpdubose** [comment]
Thank you. Give 75% of my family naps in non concurrent schedule I am kinda sorta working this wk but if I could kick the can on this one to next wk I'd appreciate it. Thank you.

**Comment by osbornm** [comment]
@rpdubose @keithresar This needs to be done through our existing google analytics tracking. There are very very very specific regulations and laws around tracking specifically in the EU and google Analytics helps make sure we adhere to those regulations and laws. Additional if any changes need to be made its in one place. 

We can add specific tracking through GA, custom fields etc. but its not just as simple as writing the code the impacts (meeting regulatory standards and laws) need to be considered first.

**Comment by rpdubose** [comment]
Agreed. Hence my comment around tribal analytics. Though eu directives kick the can to local (read: country soecific) statutes.  Though I know there's been some discussion to he contrary lately. ;)
