### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by jcoleis** [CenturyLinkCloud/PublicKB#354]
'Commvault' and 'Lagrange CloudMaestro' links on https://www.ctl.io/knowledge-base/release-notes/2015-09-01-cloud-platform-release-notes/ direct users to a 404 page.

**Comment by csterwa** [comment]
Should be assigned to @BobStolzberg since he is committing a fix for these not being out on the KB section yet.

**Comment by nathanyoung** [comment]
fix getting deployed now...
