### ISSUE TITLE
404 From Getting Started with Cloudera on CenturyLink Cloud

### ISSUE THREAD

**Issue by rpdubose** [CenturyLinkCloud/PublicKB#403]
@timjbaumgartner the Cloudera Manager Guide (pdf) is throwing a 404.  Can you pls take a look?

![image](https://cloud.githubusercontent.com/assets/5082753/9799138/fd5fe5ea-57ca-11e5-8816-edeb034a62d0.png)

**Comment by chrislittle** [comment]
fix issued, will roll out next release. for now you can get it from https://www.ctl.io/knowledge-base/managed-services/big-data-operations-guide-for-cloudera-manager-v5x-hadoop/

**Comment by chrislittle** [comment]
closing issue
