### ISSUE TITLE
Blog search is returning "browse" results

### ISSUE THREAD

**Issue by keithresar** [CenturyLinkCloud/PublicKB#421]
Searching the blog is returning both actual articles and the browse pages.  I wouldn't expect the later.

For example:
https://www.ctl.io/blog/search/?cx=004518466626182738981%3A66-q7451vko&ie=UTF-8&q=dynatrace+site%3Ahttps%3A%2F%2Fwww.ctl.io%2Fblog%2F

**Comment by nathanyoung** [comment]
won't fix
