### ISSUE TITLE
Attachment link broken in /Blueprints/using-blueprint-script-to-call-api

### ISSUE THREAD

**Issue by bmathews** [CenturyLinkCloud/PublicKB#444]
https://github.com/CenturyLinkCloud/PublicKB/blob/master/Blueprints/using-blueprint-script-to-call-api.md

https://www.ctl.io/knowledge-base/blueprints/using-blueprint-script-to-call-api/

**Comment by rpdubose** [comment]
@bmathews appears to be working for me.  Did you correct? If so, pls close.

**Comment by rpdubose** [comment]
Appears to have been corrected.  Reopen w/ detail if this is still an issue.
