### ISSUE TITLE
Markdown Compile Issue with Code Examples

### ISSUE THREAD

**Issue by hudakdidit** [CenturyLinkCloud/PublicKB#459]
@bmathews discovered an issue in a code snippet at <https://www.ctl.io/knowledge-base/afv1/logentries/>

```
require dirname(FILE) . '/le_php-master/logentries.php';
```

The markdown parser mistakenly transforms `__FILE__` to **FILE**

The solution we propose for this is to set the frontmatter flag **contentIsHTML** to `true` and replace all markdown with HTML. The majority of the content of this file and many of its siblings is HTML, so the update wouldn't be too much of a hassle (certainly less than modifying the markdown parser to handle this single case).

@nathanyoung we wanted to bring this to your attention. We're happy to make the update if needed.

@mattfordham ping

**Comment by nathanyoung** [comment]
https://github.com/CenturyLinkCloud/PublicKB/commit/f901608d9c024ff703abe6f9da10fa411cfd1c87
