### ISSUE TITLE
Category Links Broken

### ISSUE THREAD

**Issue by hudakdidit** [CenturyLinkCloud/PublicKB#469]
https://www.ctl.io/knowledge-base/ecosystem-partners/partner-integration-resources/ecosystem-program-resources-blueprints/

Link is foudn under 'Core Documentation'

**Comment by nathanyoung** [comment]
@hudakdidit This link is formatted correctly, but `gulp kb` isn't generating the link properly. The commit analyzer isn't reporting any errors, with the source article (https://github.com/CenturyLinkCloud/PublicKB/blob/master/Ecosystem%20Partners/Partner%20Integration%20Resources/ecosystem-program-resources-blueprints.md)

cc: @bmathews

**Comment by hudakdidit** [comment]
@nathanyoung gotcha. OK We'll investigate.

**Comment by nathanyoung** [comment]
Another broken category link: 
https://github.com/CenturyLinkCloud/PublicKB/blob/master/Partners/support-escalation-process-for-partners.md

Line 151.

Formatted correctly in github, but broken on https://www.ctl.io/knowledge-base/partners/support-escalation-process-for-partners/

**Comment by nathanyoung** [comment]
https://github.com/CenturyLinkCloud/PublicKB/issues/479

**Comment by mattfordham** [comment]
Should be fixed by https://github.com/CenturyLinkCloud/PublicPlatform/commit/60fff192fe7deb57ad5ea8a37c65e953c23efaa8
