### ISSUE TITLE
Broken link in /knowledge-base/afv1/custom-domain-names/#command-line-tool

### ISSUE THREAD

**Issue by hudakdidit** [CenturyLinkCloud/PublicKB#473]
file: https://github.com/CenturyLinkCloud/PublicKB/blob/master/AFv1/custom-domain-names.md

link is found under ###Command-ine Tool heading

**Comment by thenickcox** [comment]
This looks like it should just link relatively to the markdown file.

**Comment by hudakdidit** [comment]
b8831995ebea5d65f14d3e848407bbb0faf718e5

**Comment by hudakdidit** [comment]
Resolved with 6a69dc508d4bb1d1dcbdf238ec783dc821813290 and e8682cfc1199e8b9778aeb5f3ad247a303146831
