### ISSUE TITLE
Rendering issues in /afv1/memcached-cloud

### ISSUE THREAD

**Issue by hudakdidit** [CenturyLinkCloud/PublicKB#477]
https://www.ctl.io/knowledge-base/afv1/memcached-cloud/

Find beneath **Using Memcached with Python**

**Comment by csterwa** [comment]
Should be fixed in https://github.com/CenturyLinkCloud/PublicKB/pull/478

**Comment by nathanyoung** [comment]
https://github.com/CenturyLinkCloud/PublicPlatform/commit/b3a46b75743d1a8b19f6fdd71b03f4540739e63f
