### ISSUE TITLE
S3CMD - Object Storage Management 

### ISSUE THREAD

**Issue by hudakdidit** [CenturyLinkCloud/PublicKB#479]
source file: https://github.com/CenturyLinkCloud/PublicKB/blob/master/Object%20Storage/s3cmd-object-storage-management-for-linux-machines.md

Broken link is: `<a href="../Object Storage">CenturyLink Cloud Object Storage</a>`, I think this link should actually `../../object-storage`?

**Comment by nathanyoung** [comment]
I think the way it's formatted is correct. This is another case of https://github.com/CenturyLinkCloud/PublicKB/issues/469
