### ISSUE TITLE
mixed data on managed build time

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PublicKB#565]
https://www.ctl.io/knowledge-base/managed-services/managed-operating-system-frequently-asked-questions/ 
"After creating a VM for management or after deploying the blueprint to convert an existing VM to a managed one, the VM will be 'Under Construction' while background processes are completed. You will not have access to the server during that time; you will receive a notification via email once the operation has completed. Please allow up to a 60 minutes."

https://www.ctl.io/knowledge-base/managed-services/created-a-managed-server-now-what/
"You will not have access to the server during that time; you will receive a notification via email once the operation has completed (allow up to a 30 minutes)"

i'm not sure what we publicly want as the formal statement on this but my experience is that we rarely hit < 60 min. its generally in excess of 60 minutes in most situations.  

@jruckle

**Comment by rpdubose** [comment]
@robcaldwell could chime in on this?

**Comment by rpdubose** [comment]
@robcaldwell We'll leave this open for another wk but then will close it down assuming it as addressed outside of GitHub.
