### ISSUE TITLE
Commit Analyzer Not Working

### ISSUE THREAD

**Issue by rpdubose** [CenturyLinkCloud/PublicKB#705]
@mattfordham think you fellows have always helped us get the commit analyzer back up when we've seen issues.  Who can @jim-phillips work w/ to learn more about it so we can self manage?

Thanks,
Rich

**Comment by mattfordham** [comment]
I'd be happy to help. Feel free to have @jim-phillips reach out via email ... matt@wintr.us

**Comment by mattfordham** [comment]
Or here, if that's preferable
