### ISSUE TITLE
ticket-prioritization-matrix.md

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/PublicKB#81]
the ticket prioritization matrix update doesn't have a break delineating the service task matrix area from the support request area.  the table just jumps without a header break which is confusing when viewing as you have no idea why this new table just appeared and what its clearly for.  we should add a ### Service Task header or something ahead of it

**Comment by nathanyoung** [comment]
You're right, I think I accidentally ommited that.
