### ISSUE TITLE
Update Backup/DR KB by removing Standard/Premium backup options

### ISSUE THREAD

**Issue by jruckle** [CenturyLinkCloud/PublicKB#882]
https://www.ctl.io/knowledge-base/servers/centurylink-cloud-backup-and-recovery-services/

@chrislittle - i can update this too if you like, but didn't want to edit your stuff without your blessing.

**Comment by chrislittle** [comment]
@jruckle ya this whole kb needs a complete re-write to include SBS, managed backup, ecosystem tools etc.  when do you need this done by?

**Comment by jruckle** [comment]
Just doing my scrub of materials - end of March would be ideal once SBS is live

**Comment by jruckle** [comment]
same with this one @chrislittle : https://www.ctl.io/knowledge-base/servers/disaster-recovery-comparison-matrix/

**Comment by chrislittle** [comment]
dr matrix removed: https://github.com/CenturyLinkCloud/PublicKB/pull/885

**Comment by chrislittle** [comment]
completed:  https://github.com/CenturyLinkCloud/PublicKB/pull/902
