### ISSUE TITLE
Scrub Premium from https://www.ctl.io/knowledge-base/servers/understanding-vm-deployment-options-and-power-states/

### ISSUE THREAD

**Issue by jruckle** [CenturyLinkCloud/PublicKB#887]
At the very end of the article, the line about `Premium` should be scrubbed:

Note: Archived servers are not backed up or replicated (for premium storage customers) daily. Rather, only a single copy of the server exists. To restore a VM in which you have archived, simply unarchive it.

**Comment by chrislittle** [comment]
completed in https://github.com/CenturyLinkCloud/PublicKB/pull/889
