### ISSUE TITLE
Update VM Import KB: https://www.ctl.io/knowledge-base/service-tasks/best-practices-and-preparation-for-a-virtual-machineovfova-import/

### ISSUE THREAD

**Issue by jruckle** [CenturyLinkCloud/PublicKB#888]
scrub this section:

`Type of Storage (Standard or Premium) to be used for the Virtual Machine(s). Applies to Standard virtual server type only.`

Or @jmalmadclc i can do this on your behalf?

**Comment by jmalmadclc** [comment]
Of course, any edits w/r/t to Prem/Standard that you see and need to fix- feel free…

Jacob Malmad
Sr. Cloud Architect
CenturyLink Cloud 
Mobile: 203.844.0516
Email: jake.malmad@centurylink.com<mailto:jake.malmad@centurylinkcloud.com> 
www.centurylinkcloud.com<http://www.centurylinkcloud.com/>

**Comment by chrislittle** [comment]
completed per https://github.com/CenturyLinkCloud/PublicKB/pull/890
