### ISSUE TITLE
The URL for the download does not exist

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/PublicKB#975]
Hi SafeHaven team,
In KB (https://www.ctl.io/knowledge-base/disaster-recovery/build-safehaven-base-image-template-from-ubuntu/), the URL https://www.dropbox.com/sh/7837hqfwe31wzrh/AADGn34eQ25IDLw4_VOmsRWya/SH3.1.1-u1-Testing/baseInstaller-SafeHaven3.1.1-u1.tar.gz?dl=0 is not valid anymore.
Should this still be valid or a new version is available at another location?
Thanks
Gavin

**Comment by chrislittle** [comment]
@jmalmadclc see this issue....link in KB for SH not working

**Comment by chrislittle** [comment]
@jmalmadclc can you fix this?

**Comment by chrislittle** [comment]
fixed in https://github.com/CenturyLinkCloud/PublicKB/pull/1050
